### ISSUE TITLE
Error while running pysoc.py file

### ISSUE THREAD

**Issue by priyanandchem** [jzpathfinder/pysoc#12]
Hello sir .
I'm using the g09 version and got this error while running the pySOC.py file
QM_code gauss_tddft
open file bt-soc.log
[[1, 2.595], [2, 3.6078], [3, 4.3647], [5, 4.3852], [6, 5.2711]]
4 4.3821
Error when reading gaussian output
Traceback (most recent call last):
  File "/home/tanmoy/Downloads/pySOC-cal/pysoc/bin/soc.py", line 491, in <module>
    write_file(mo_ene, 'mo_ene.dat', '{}  ')
NameError: name 'mo_ene' is not defined
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 171, file /home/tanmoy/Downloads/pySOC-cal/cals/soc_td_input.dat
Image              PC                Routine            Line        Source            
soc_td             000000000048B27E  Unknown               Unknown  Unknown
soc_td             0000000000489D16  Unknown               Unknown  Unknown
soc_td             0000000000449EF2  Unknown               Unknown  Unknown
soc_td             000000000041ECCB  Unknown               Unknown  Unknown
soc_td             000000000041E232  Unknown               Unknown  Unknown
soc_td             00000000004287F8  Unknown               Unknown  Unknown
soc_td             000000000040755A  Unknown               Unknown  Unknown
soc_td             00000000004022D9  Unknown               Unknown  Unknown
soc_td             000000000040227C  Unknown               Unknown  Unknown
libc.so.6          00002B9319C1B555  Unknown               Unknown  Unknown
soc_td             0000000000402179  Unknown               Unknown  Unknown

_Originally posted by @priyanandchem in https://github.com/gaox-qd/pysoc/issues/5#issuecomment-2095196486_

**Comment by bairobbi** [comment]
Hello, I also came across this error while running pysoc.py with g16. I modified the code following the tutorial in http://bbs.keinsci.com/thread-19813-1-1.html 
I received this output:

QM_code gauss_tddft
open file gauss-b18tddft.log
[[1, 3.2691], [3, 4.3303], [4, 4.3304], [5, 4.7118], [8, 4.9229], [9, 4.9952], [11, 5.1758], [13, 5.2692], [14, 5.318], [16, 5.3256]]
2 3.8865
['ANG', 'Zeff', 'DIP']
Error when reading gaussian output
Traceback (most recent call last):
  File "/users/rbai/sob_PySOC_MolSOC/pysoc/bin/soc.py", line 491, in <module>
    write_file(mo_ene, 'mo_ene.dat', '{}  ')
NameError: name 'mo_ene' is not defined
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 171, file /users/rbai/Gaussian/soc_td_input.dat
Image              PC                Routine            Line        Source
soc_td             000000000041BBB6  Unknown               Unknown  Unknown
soc_td             0000000000427AEB  Unknown               Unknown  Unknown
soc_td             0000000000407F0B  Unknown               Unknown  Unknown
soc_td             000000000040254E  Unknown               Unknown  Unknown
soc_td             00000000004024FE  Unknown               Unknown  Unknown
libc.so.6          00002AB3DE35F555  Unknown               Unknown  Unknown
soc_td             0000000000402409  Unknown               Unknown  Unknown


Do you have any suggestions on how to alter the code to fix this error?

**Comment by gibbs8** [comment]
I encountered a similar error.
In my case, the output was this:

QM_code gauss_tddft
open file gaussian.log
[]
1 2.8406
['ANG', 'Zeff', 'DIP']
Error when reading gaussian output
Traceback (most recent call last):
  File "/home/denis/pysoc-1.0/pysoc/bin/soc.py", line 491, in <module>
    write_file(mo_ene, 'mo_ene.dat', '{}  ')
NameError: name 'mo_ene' is not defined
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 171, file /media/denis/HDD6/umbrella/1,2-RH-addition/Methane_clathrate/g09/TD-DFT/S1_pysoc/soc_td_input.dat
Image              PC                Routine            Line        Source             
soc_td             000000000048B27E  Unknown               Unknown  Unknown
soc_td             0000000000489D16  Unknown               Unknown  Unknown
soc_td             0000000000449EF2  Unknown               Unknown  Unknown
soc_td             000000000041ECCB  Unknown               Unknown  Unknown
soc_td             000000000041E232  Unknown               Unknown  Unknown
soc_td             00000000004287F8  Unknown               Unknown  Unknown
soc_td             000000000040755A  Unknown               Unknown  Unknown
soc_td             00000000004022D9  Unknown               Unknown  Unknown
soc_td             000000000040227C  Unknown               Unknown  Unknown
libc.so.6          0000151B7D64ED0A  Unknown               Unknown  Unknown
soc_td             0000000000402179  Unknown               Unknown  Unknown

It turned out that the problem was in the soc.py file.
This script contains the following fragment:

           for line in lines:
               if line.split()[0] in shell:
                  sub_orb = line.split()[0]
                  pair = [sub_orb, shell[sub_orb]]
                  ao_basis.append(pair)
               if len(line.split()) == 2 and re.search(r'\d \d', line):
                   line = '{}  {}\n'.format(element[i], line.split()[1])
                   i += 1
               f.write(line)

This fragment does not work properly if line == '\n'. The problem was solved by replacing the above fragment with the following:

           for line in lines:
               parts = line.split()
               if parts and parts[0] in shell:
                   sub_orb = parts[0]
                   pair = [sub_orb, shell[sub_orb]]
                   ao_basis.append(pair)
               if len(line.split()) == 2 and re.search(r'\d \d', line):
                   line = '{}  {}\n'.format(element[i], line.split()[1])
                   i += 1
               f.write(line)
