### ISSUE TITLE
PySOC running issue

### ISSUE THREAD

**Issue by iamshahboz** [jzpathfinder/pysoc#15]
Dear developers.
I am trying to do Spin-Orbit Coupling calculation with PySoc

I am using Python 3.10.12

What I have done so far (I am on WSL, since in GitHub the installation was on Linux-based systems)
1. Cloned the repository
2. Created a virtual environment and activated it
3. Installed the packages
4. Set PYTHONPATH and PATH to the environment variables
5. changed the directory to the ch20_gaussian folder where gaussian.log and gaussian.rwf located
7. run the command
pysoc gaussian.log  --rwf_file gaussian.rwf

And I get this error

Traceback (most recent call last):
  File "/home/shahboz/pysoc/pysoc/io/SOC.py", line 106, in calculate
    self.molsoc.parse()
  File "/home/shahboz/pysoc/pysoc/io/gaussian.py", line 363, in parse
    self.parse_RWF()
  File "/home/shahboz/pysoc/pysoc/io/gaussian.py", line 205, in parse_RWF
    self.MO_energies = rwf_parser.parse(rwf_parser.MO_ENERGY, self.num_orbitals)[self.num_frozen_orbitals:]
  File "/home/shahboz/pysoc/pysoc/io/gaussian.py", line 114, in parse
    dumped_data = self.get_section(code)[1]
  File "/home/shahboz/pysoc/pysoc/io/gaussian.py", line 62, in get_section
    rwfdump_proc =  subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rwfdump'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shahboz/pysoc/bin/pysoc", line 107, in <module>
    main(
  File "/home/shahboz/pysoc/bin/pysoc", line 54, in main
    SOC.calculate(output = output, SOC_scale = SOC_scale, include_ground = include_ground, CI_coefficient_threshold = CI_coefficient_threshold)
  File "/home/shahboz/pysoc/pysoc/io/SOC.py", line 108, in calculate
    raise Exception("Failed to parse QM output file") from e
Exception: Failed to parse QM output file

How can I fix it.

**Comment by wengivis** [comment]
Hello,

I am only a user, but we also had that same error message on our cluster. To solve it, we had to module load Gaussain, which we used for the calculations.
My suspicion is the pysoc program is using some of the programs of Gaussian and it needs access to those.

Hope this helps.
Best regards,
Péter

**Comment by iamshahboz** [comment]
@wengivis 
I will try, thanks a lot. I do appreciate it
